/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KhoaHocRouteImport } from './routes/khoa-hoc'
import { Route as NangLucRouteImport } from './routes/nang-luc'
import { Route as NguonTaiLieuRouteImport } from './routes/nguon-tai-lieu'
import { Route as TheCuaToiRouteImport } from './routes/the-cua-toi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KhoaHocRoute = KhoaHocRouteImport.update({
  id: '/khoa-hoc',
  path: '/khoa-hoc',
  getParentRoute: () => rootRouteImport,
} as any)
const NangLucRoute = NangLucRouteImport.update({
  id: '/nang-luc',
  path: '/nang-luc',
  getParentRoute: () => rootRouteImport,
} as any)
const NguonTaiLieuRoute = NguonTaiLieuRouteImport.update({
  id: '/nguon-tai-lieu',
  path: '/nguon-tai-lieu',
  getParentRoute: () => rootRouteImport,
} as any)
const TheCuaToiRoute = TheCuaToiRouteImport.update({
  id: '/the-cua-toi',
  path: '/the-cua-toi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/khoa-hoc': typeof KhoaHocRoute
  '/nang-luc': typeof NangLucRoute
  '/nguon-tai-lieu': typeof NguonTaiLieuRoute
  '/the-cua-toi': typeof TheCuaToiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/khoa-hoc': typeof KhoaHocRoute
  '/nang-luc': typeof NangLucRoute
  '/nguon-tai-lieu': typeof NguonTaiLieuRoute
  '/the-cua-toi': typeof TheCuaToiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/khoa-hoc': typeof KhoaHocRoute
  '/nang-luc': typeof NangLucRoute
  '/nguon-tai-lieu': typeof NguonTaiLieuRoute
  '/the-cua-toi': typeof TheCuaToiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/khoa-hoc' | '/nang-luc' | '/nguon-tai-lieu' | '/the-cua-toi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/khoa-hoc' | '/nang-luc' | '/nguon-tai-lieu' | '/the-cua-toi'
  id:
    | '__root__'
    | '/'
    | '/khoa-hoc'
    | '/nang-luc'
    | '/nguon-tai-lieu'
    | '/the-cua-toi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KhoaHocRoute: typeof KhoaHocRoute
  NangLucRoute: typeof NangLucRoute
  NguonTaiLieuRoute: typeof NguonTaiLieuRoute
  TheCuaToiRoute: typeof TheCuaToiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/khoa-hoc': {
      id: '/khoa-hoc'
      path: '/khoa-hoc'
      fullPath: '/khoa-hoc'
      preLoaderRoute: typeof KhoaHocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nang-luc': {
      id: '/nang-luc'
      path: '/nang-luc'
      fullPath: '/nang-luc'
      preLoaderRoute: typeof NangLucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nguon-tai-lieu': {
      id: '/nguon-tai-lieu'
      path: '/nguon-tai-lieu'
      fullPath: '/nguon-tai-lieu'
      preLoaderRoute: typeof NguonTaiLieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/the-cua-toi': {
      id: '/the-cua-toi'
      path: '/the-cua-toi'
      fullPath: '/the-cua-toi'
      preLoaderRoute: typeof TheCuaToiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KhoaHocRoute: KhoaHocRoute,
  NangLucRoute: NangLucRoute,
  NguonTaiLieuRoute: NguonTaiLieuRoute,
  TheCuaToiRoute: TheCuaToiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
